version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[transformers]]
name = "prettier"